### ISSUE TITLE
no value accessor for form control error in new version of igniteui-angular2

### ISSUE THREAD

**Issue by JiaLiPassion** [IgniteUI/igniteui-angular-wrappers#245]
### Description  
Describe the issue.

### Steps to reproduce  

1. create a angular project with dynamic component
2. add the dynamic component into form
3. `no value accessor for form control` error will throw.

the same code works in `igniteui-angular2` 4.1.1, but not work in the newest version. 
I can't create a reproduce repo because the code was mixed in a big project. And currently it seems 
`igniteui-angular-wrappers` 5.0.3 not workable. 

the error because this line ,

https://github.com/IgniteUI/igniteui-angular-wrappers/blob/master/src/igeditors/igeditorbase.ts#L10

the `model` is `null` even I define an `ignite` control with `ngModel`  as following.

```javascript
<form>
<ig-text-editor widgetId="compId" 
                [(ngModel)]="somedata"
                [options]='textOptions'
                [ngModelOptions]="{standalone: true}">
</form>
```

**Comment by damyanpetev** [comment]
I got the same result when using the `IgniteUIModule`. However, if you directly declare the component instead from 
`import {  IgTextEditorComponent } from "igniteui-angular-wrappers/igeditors/igtexteditor.component";` 
it seems to accept the model just fine.

@JiaLiPassion Are you importing the `IgniteUIModule` too?

@dkamburov: 
Might have to do with a change in the Angular forms module from 4 to 5..somehow. We don't technically use `ngModule` in our templates, but we do implement value accessor, so worth a try to import it in our own module, since that's the main difference.

**Comment by JiaLiPassion** [comment]
I think I have found the reason, because `igniteui-angular2.umd.js` rollup the `@angular` source into it, so there will be 2 versions of `@angular/core`, `@angular/forms` and so on...

I just modified `node_modules/igniteui-angular2/package.json` and change `main` from `igniteui-angular2.umd.js` to `igniteui.angular2.js`.

```javascript
"main": "igniteui.angular2.js"
```
and everything work fine.

**Comment by damyanpetev** [comment]
@JiaLiPassion Quite right! 👏 
`@angular/core` was properly ignored, but `@angular/forms` wasn't (that dragged along some rxjs in there too I believe). That's why only `ngModel` operations had an issue. PR incoming in a bit.
