### ISSUE TITLE
Missing typings for Doughnut Chart

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular-wrappers#271]
Missing typings for Doughnut Chart in **index.d.ts** 

1. Use the Igniteui-CLI to create angular ts(igniteui-angular-wrappers) project via the wizard and add a Doughnut Chart.
2. Complete and run..

### Result  
Chart is rendered with:
error TS2304: Cannot find name 'IgDoughnutChart'.
... ./src/app/components/doughnut-chart/doughnut-chart.component.ts

### Expected result  
To find the typing and run as expected without errors.

### Attachments  
![image](https://user-images.githubusercontent.com/4296944/40000206-e85590de-5793-11e8-892e-3d1d2590ba38.png)

**Comment by skrustev** [comment]
It seems that the parsing of the Doughnut Chart fails because the locale is put inside the `infragistics.ui.doughnutchart.js` file.

@gmurray81 I assume you would know if it is possible to not have the locale there and somewhere separate? Otherwise we would need to remember to remove the locale manually every time we update the typings.

**Comment by dkamburov** [comment]
Resolved with the latest version of the [@types/ignite-ui](https://www.npmjs.com/package/@types/ignite-ui) (18.1.1)
